output "name" {
  value = var.project
}

# VPC ID
output "vpc_id" {
  description = "The ID of the VPC"
  value       = module.vpc.vpc_id
}

# VPC Private Subnets
output "private_subnets" {
  description = "List of IDs of private subnets"
  value       = module.vpc.private_subnets
}

# VPC Public Subnets
output "public_subnets" {
  description = "List of IDs of public subnets"
  value       = module.vpc.public_subnets
}

# VPC NAT gateway Public IP
output "nat_public_ips" {
  description = "List of public Elastic IPs created for AWS NAT Gateway"
  value       = module.vpc.nat_public_ips
}

output "cluster_endpoint"{
  description = "EKS Cluster control plane endpoint"
  value       = module.eks.cluster_endpoint
}

output "eks_kubeconfig" {
  description = "EKS Cluster kube config generated by module"
  value       = module.eks.kubeconfig
}

output "cluster_security_group_id" {
  description = "EKS Cluster security group id"
  value       = module.eks.cluster_security_group_id
}
