FROM public.ecr.aws/docker/library/php:7.4-apache

# Set ENV variables 
# Update DB connection to point to a K8s service named mysql-service.
ENV DB_HOST mysql-service
ENV DB_USER ecomuser
ENV DB_PASSWORD ecompassword
ENV DB_NAME ecomdb

# Install mysqli extension for PHP
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

# Copy the application source code to /var/www/html/
COPY . /var/www/html/

# Expose port 80 to allow traffic to the web server
EXPOSE 80
