apiVersion: storage.k8s.io/v1 
kind: StorageClass
metadata:
  name: aws-ssd-storage
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
  csi.storage.k8s.io/fstype: xfs
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer 
reclaimPolicy: Delete # Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  labels:
    app: ecom-app
    tier: db
spec:
  storageClassName: aws-ssd-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
