# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mariadb-pv
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOncePod
#   hostPath:
#     path: "/mnt/data"

# ---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 2Gi
