apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-app
      tier: frontend
  template:
    metadata:
      labels:
        app: ecom-app
        tier: frontend
    spec:
      containers:
        - name: php
          image: 533267165479.dkr.ecr.eu-west-2.amazonaws.com/k8s-resume-challenge:v1.0
          imagePullPolicy: Always
          resources: {}
          ports:
            - name: http
              containerPort: 80
          env:
          - name: DB_HOST
            value: "mysql-service"
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: mariadb-config
                key: mysql_user
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mariadb-config
                key: mysql_db
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: mysql_password
          - name: FEATURE_DARK_MODE
            valueFrom:
              configMapKeyRef:
                name: feature-toggle-config
                key: FEATURE_DARK_MODE
          - name: MESSAGE
            value: "Hello k8s world!"
          # command: ["service apache2 restart"]