apiVersion: v1
kind: Service
metadata:
  name: website-service
  labels:
   app: website-service
spec:
  type: LoadBalancer
  selector:
    app: website-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
